"""Init schema

Revision ID: c3e514f72ae5
Revises: 
Create Date: 2023-03-22 16:06:15.496608

"""
import uuid

from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union

from sqlalchemy import ARRAY, VARCHAR
from sqlalchemy.dialects.postgresql import JSONB, UUID
# revision identifiers, used by Alembic.
revision = 'c3e514f72ae5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("token", sa.Text, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP, server_default=sa.func.now(),
                  onupdate=sa.func.current_timestamp(), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'users',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("name", sa.String(255), unique=False, nullable=False),
        sa.Column("password", sa.String(255), unique=False, nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
        sa.Column("reset_token", sa.String(255), nullable=True, default=False),
        sa.Column("reset_token_expires", sa.DateTime(), nullable=True, default=False),
        sa.Column("facebook_id", sa.String(255), nullable=True, default=False),
        sa.Column("google_id", sa.String(255), nullable=True, default=False),
        sa.Column("github_id", sa.String(255), nullable=True, default=False),
        sa.Column("twitter_id", sa.String(255), nullable=True, default=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
    )
    op.create_table(
        'package_repos',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
        sa.UniqueConstraint("user_id", "name", name="uq_package_repos_user_name"),
    )
    op.create_table(
        'product_types',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'resource_platforms',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'resource_stages',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'resource_statuss',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'resource_tags',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
        sa.UniqueConstraint("user_id", "name", name="uq_resource_tags_user_name"),
    )
    op.create_table(
        'permissions',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, server_default=sa.false()),
    )
    op.create_table(
        'sessions',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column('access_token', sa.String(255), unique=False, nullable=True),
        sa.Column('refresh_token', sa.String(255), unique=False, nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, server_default=sa.false()),
    )
    op.create_table(
        'resources',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("name", sa.String(255), unique=True, nullable=False),
        sa.Column('version', sa.String(255), nullable=False),
        sa.Column("stage_id", UUID(as_uuid=True), nullable=True),
        sa.Column("status_id", UUID(as_uuid=True), nullable=True),
        sa.Column("platform_id", UUID(as_uuid=True), nullable=True),
        sa.Column("product_type_id", UUID(as_uuid=True), nullable=True),
        sa.Column("repo_id", UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
        sa.Column('url', sa.String(255), unique=False, nullable=True),
        sa.Column('group_id', UUID(as_uuid=True), nullable=True),
    )
    op.create_table(
        'resource_shares',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("resource_id", UUID(as_uuid=True), sa.ForeignKey("resources.id"), nullable=False),
        sa.Column("shared_with_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("can_edit", sa.BOOLEAN, nullable=False, server_default=sa.false()),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.UniqueConstraint("resource_id", "shared_with_user_id", name="uq_resource_shares_resource_user"),
    )
    op.create_table(
        'resource_has_resource_tags',
        sa.Column('resource_id', UUID(as_uuid=True), unique=False, nullable=False),
        sa.Column('resource_tag_id', UUID(as_uuid=True), unique=False, nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN, default=False),
    )
    op.create_table(
        'organizations',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column('name', sa.String(255), unique=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(),server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN, default=False),
    )
    op.create_table(
        'user_has_permissions',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column('user_system_id', UUID(as_uuid=True), unique=False, nullable=False),
        sa.Column('permission_id', UUID(as_uuid=True), unique=False, nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN, default=False),
    )
    op.create_table(
        'system_info',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("system_name", sa.String(255), nullable=False, default="Hệ thống quản lý tài nguyên"),
        sa.Column("status", sa.String(50), nullable=False, default="Online"),
        sa.Column("version", sa.String(50), nullable=False, default="v1.0.0"),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN, nullable=False, default=False),
    )
    op.create_table(
        'notifications',
        sa.Column("id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4(), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("type", sa.String(50), nullable=False, server_default="system"),
        sa.Column("source", sa.String(50), nullable=False, server_default="system"),
        sa.Column("payload", JSONB, nullable=True),
        sa.Column("link", sa.String(512), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("read_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_is_read", "notifications", ["is_read"])
    op.create_index(op.f("ix_blacklist_tokens_id"), "blacklist_tokens", ["id"], unique=True)
    op.create_index(op.f("ix_blacklist_tokens_token"), "blacklist_tokens", ["token"], unique=True)
    
    # Insert basic user permissions
    basic_permissions = [
        "view_resources",      # Xem tài nguyên
        "upload_resources",    # Upload tài nguyên  
        "view_file_types",     # Xem loại file
        "view_categories",     # Xem danh mục
        "view_uploads",        # Xem uploads
        "view_profile"         # Xem profile
    ]
    
    # Enable uuid-ossp extension
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
    
    for permission in basic_permissions:
        op.execute(f"""
            INSERT INTO permissions (id, name, is_deleted) 
            VALUES (uuid_generate_v4(), '{permission}', false)
        """)
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Delete basic user permissions first
    basic_permissions = [
        "view_resources",
        "upload_resources", 
        "view_file_types",
        "view_categories",
        "view_uploads",
        "view_profile"
    ]
    
    for permission in basic_permissions:
        op.execute(f"DELETE FROM permissions WHERE name = '{permission}'")
    
    
    op.drop_table('blacklist_tokens')
    op.drop_table('package_repos')
    op.drop_table('product_types')
    op.drop_table('resource_platforms')
    op.drop_table('resource_stages')
    op.drop_table('resource_statuss')
    op.drop_table('resource_tags')
    op.drop_table('permissions')
    op.drop_table('sessions')
    op.drop_table('resource_shares')
    op.drop_table('resources')
    op.drop_table('users')
    op.drop_table('resource_has_resource_tags')
    op.drop_table('organizations')
    op.drop_table('user_has_permissions')
    op.drop_table('system_info')
    op.drop_index("ix_notifications_is_read", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_table('notifications')
    # ### end Alembic commands ###
